### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alercah** [Euophrys/mahjong-discord-bot#2]
What license is this code under?

**Comment by jmbtutor** [comment]
I had assumed it was under the [ISC](https://spdx.org/licenses/ISC). At least, that's what the `package.json` says.

https://github.com/Euophrys/mahjong-discord-bot/blob/35a730a0a81a09f66034fc667d8a00285e54ca93/package.json#L15

This is a good question, though, because the ISC is the default when creating a new npm package, so there's a chance that putting it under that license was unintentional.

**Comment by alercah** [comment]
Ah, I think that would do it. I didn't dig into any files since I didn't see a LICENSE file.

**Comment by Euophrys** [comment]
Ah, I forgot to add one. I probably would have set it as GNU GPL v3.0, but I'm not really picky, so ISC is fine.

**Comment by Euophrys** [comment]
... Except github doesn't have ISC in its selector so I'll just add GNU GPL v3.0.
